[package]
name = "spl-memo"
version = "4.0.0"
description = "Solana Program Library Memo Program"
authors = ["Solana Maintainers"]
repository = "https://github.com/hamkj7hpo/memo"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.1.1"

[patch.crates-io]
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", branch = "safe-pump-compat" }
